### ISSUE TITLE
RVIZ not showing

### ISSUE THREAD

**Issue by xinghuitao** [kimbring2/jetbot_soccer#1]
![Screenshot from 2020-01-30 12-08-41](https://user-images.githubusercontent.com/46446128/73448698-55de3e00-4359-11ea-8a54-06452434fef8.png)

Hi,

I run "roslaunch jetbot_description jetbot_rviz.launch" and cannot show the jetbot model in RVIZ. What might be the problems? Thanks!

Regards
Tao

**Comment by kimbring2** [comment]
Oh, sorry. 

I accidentally touched the file during modification.
To solve that issue, you should add below code in the first part jetbot.xacro file.

`
''''
<xacro:include filename="$(find jetbot_description)/urdf/jetbot.gazebo" />


<link name="world"/>

<joint name="fixed" type="fixed">
  <parent link="world"/>
  <child link="chassis"/>
</joint>

<link name="chassis">
''''
`
Sorry for inconvenience,
From Dohyeong

**Comment by xinghuitao** [comment]
Hi, Dohyeong

Thanks a lot! 
The jetbot shows up, but the camera is receiving images. I run "rostopic echo /tf | grep -i camera_link", which show nothing. 
Can you pls look into it as well? 
Thanks, I might have to bother you a lot in the future...:P

Regards
Tao

**Comment by kimbring2** [comment]
Welcome, Xinghuitao. 

Did you run a 'roslaunch jetbot_gazebo main.launch' before listing rostopic?
RVIZ is not for brocasting rospotic. You should launch a Gazebo instead of it.

Please ask me about project. I will do my best to help.

Sincerely,
Dohyeong Kim

**Comment by xinghuitao** [comment]
Hi, Dohyeong

Thanks in advance. What I trying to solve is:

![Screenshot from 2020-01-31 14-14-18](https://user-images.githubusercontent.com/46446128/73545881-22bcad00-4434-11ea-9187-4c6abb20e858.png)

Thanks
Xinghui

**Comment by kimbring2** [comment]
Hi, Xinghui

Thank you for testing. You are doing right.

The reason I changed my existing jetbot.xacro file is that if I put in a world link, the Jetbot would be abnormally placed on Gazebo. To solve these problems fundamentally, I make separate xacro files for Rviz. Now that the repository has been updated, you can use it.

Sincerely,
From Dohyeong

**Comment by xinghuitao** [comment]
Thanks!
