### ISSUE TITLE
Could not load controller

### ISSUE THREAD

**Issue by xinghuitao** [kimbring2/jetbot_soccer#2]
Hi, Dohyeong

I am making progress step by step. Now I get to the stage below:

![Screenshot from 2020-02-02 16-31-11](https://user-images.githubusercontent.com/46446128/73611443-d27f4f80-45d9-11ea-9db3-afac8e9d0626.png)

Anything I missed?

Regards
Xinghui

**Comment by xinghuitao** [comment]
BTW, when U install tensorflow and opencv-python/cvlib, R they under python2 or python3 env?

Thanks again!

**Comment by kimbring2** [comment]
@xinghuitao Oh, hi.

I am using a python 2. Gazebo simulation supports only version 2. 
I am checking a issue of cotronller. Please wait little more!!

Thank you,
From Dohyeong

**Comment by xinghuitao** [comment]
After I installed tensorflow and cvlib. "the controller cannot find" error is gone. However, there is another one error showing: "No p gain sepecified for pid". 

![Screenshot from 2020-02-02 21-34-35](https://user-images.githubusercontent.com/46446128/73615846-d7f18f80-4603-11ea-8042-d9155880b72c.png)

Thanks!
From Xinghui

**Comment by xinghuitao** [comment]
I found out the pid error is not actually an error by this link. 
https://answers.ros.org/question/293830/what-is-the-fix-for-no-p-gain-specified-for-pid-namespace-gazebo_ros_controlpid_gainsback_right_wheel_joint-ros-melodic/

**Comment by kimbring2** [comment]
@xinghuitao Oh, I can also see PID error. But, it dose not effect to program.

**Comment by xinghuitao** [comment]
@kimbring2 I repeated the process. This time I installed tensorflow-gpu and cvlib first. The  "the controller cannot find" error showed up again.

**Comment by xinghuitao** [comment]
@kimbring2 I manually installed "sudo apt-get install ros-melodic-effort-controllers". Now it shows: 
![Screenshot from 2020-02-03 14-25-23](https://user-images.githubusercontent.com/46446128/73660917-0bc6c680-4691-11ea-9fb5-63ff12117043.png)

**Comment by kimbring2** [comment]
@xinghuitao Hmm, is it happened when you run a 'roslaunch jetbot_gazebo main.launch'? That process is not related with python directly. But, installing python package is giving some effect to it.

**Comment by kimbring2** [comment]
@xinghuitao Can you try to run that tutorial? http://gazebosim.org/tutorials/?tut=ros_urdf. My code is based on that code. I think it will give some clue about problem.

**Comment by xinghuitao** [comment]
Sure. 
Yes, I was running "roslaunch jetbot_gazebo main.launch".
I moved this to another topic. The "the controller cannot find" is solved by  "sudo apt-get install ros-melodic-effort-controllers".
