### ISSUE TITLE
Exception thrown while initializing controller

### ISSUE THREAD

**Issue by xinghuitao** [kimbring2/jetbot_soccer#3]
![Screenshot from 2020-02-03 14-25-23](https://user-images.githubusercontent.com/46446128/73663223-0e2b1f80-4695-11ea-9fe3-eb041594f6c8.png)

**Comment by xinghuitao** [comment]
@kimbring2 can you please check if you got an email from taoxh@hotmail.com to your gmail account?
Thanks a lot!

**Comment by kimbring2** [comment]
@xinghuitao Hello, I find a resaon of error message. I did not update a 'jetbot_control.yaml' file on Github. It is totally my fault.

It should be changed to like a below.
`
# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50  
  
# Position Controllers ---------------------------------------
joint1_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: left_wheel_hinge
  pid: {p: 100.0, i: 0.01, d: 10.0}
joint2_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: right_wheel_hinge
  pid: {p: 100.0, i: 0.01, d: 10.0}
`

I am really sorry for wasting time.

P.S. I check your email. Please wait little more for response! I am really interested in making Autonomous drone.

Sincerely,

**Comment by xinghuitao** [comment]
@kimbring2 I updated the yaml, yet the error is still there. Then I followed the link: https://github.com/HumaRobotics/mybot_gazebo_tutorial/issues/4 and changed: 
"<hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>"
to
"<hardwareInterface>EffortJointInterface</hardwareInterface>"
in jetbot.xacro file. 

Then the error is gone. Can you tell me the differences?
Thanks a lot!
Xinghui Tao

**Comment by kimbring2** [comment]
@xinghuitao Can you download whole repository and try run again? I also check it works without error message. We need to use same code. I begin to get confused.

Thank you.

**Comment by xinghuitao** [comment]
@kimbring2  Sure
On the readme, it says "git clone https://github.com/kimbring2/jetbot_gazebo.git" or I should download the jetbot_football.git?

**Comment by xinghuitao** [comment]
@kimbring2 You are right. The jetbot_soccer.git works!

One minor point: on the "Soccer model path setting" documentation, the jetbot.world file needs to be changed as well. 

Thanks!
Xinghui Tao

**Comment by xinghuitao** [comment]
I closed this one now. everything works~I can see the training starts. Bravo!
