### ISSUE TITLE
Initializing controller failed

### ISSUE THREAD

**Issue by xinghuitao** [kimbring2/jetbot_soccer#4]
Hi, @kimbring2 

I tried to reproduce the whole process on my desktop. The "Initializing controller failed" shows again. 

![Screenshot from 2020-02-06 10-14-51](https://user-images.githubusercontent.com/46446128/73927706-c80ad180-48c9-11ea-8f41-650ca8378b3b.png)

Any hints?

Thanks
Xinghui

**Comment by xinghuitao** [comment]
hi @kimbring2 

any updates on it. I tried the latest clone and it still shows the same error. thanks!

Tao

**Comment by xinghuitao** [comment]
sorry, I forgot to install ros-melodic-ros-control ros-melodic-ros-controllers. everything works now.

**Comment by kimbring2** [comment]
@xinghuitao Sorry, Xing. 

I am really busy because I am going to visit GTC20 for demonstrating this project. 

Sorry for not much help )-:
